### ISSUE TITLE
development.ini not recreated after destroy/up

### ISSUE THREAD

**Issue by brew** [okfn/ckan-chef#1]
development.ini is created in the synced_folder/config directory which is a synced folder on the host machine. Synced folders aren't destroyed when `vagrant destroy` is used. If we redeploy with `vagrant up` after destroying, the development.ini file isn't replaced with a fresh one, so config details such as datastore urls are present. This causes problems when trying to create databases with `paster db init` as the datastore tables are specified in the development.ini file, but haven't been created in the database yet.

**Comment by Vanuan** [comment]
I still have this:

```
==> default: Recipe Compile Error in /tmp/vagrant-chef/c701bf572f7173b605faa42f76a80d79/cookbooks/ckan/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: Errno::ENOENT
==> default: -------------
==> default: No such file or directory @ rb_sysopen - /etc/ckan/default/development.ini
==> default: 
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /tmp/vagrant-chef/c701bf572f7173b605faa42f76a80d79/cookbooks/ckan/recipes/ckan_production.rb:6:in `read'
==> default: 
==> default:   /tmp/vagrant-chef/c701bf572f7173b605faa42f76a80d79/cookbooks/ckan/recipes/ckan_production.rb:6:in `block in from_file'
==> default: 
==> default:   /tmp/vagrant-chef/c701bf572f7173b605faa42f76a80d79/cookbooks/ckan/recipes/ckan_production.rb:5:in `from_file'
==> default: 
==> default:   /tmp/vagrant-chef/c701bf572f7173b605faa42f76a80d79/cookbooks/ckan/recipes/default.rb:12:in `from_file'
```
